"""add column age in register

Revision ID: 03bd634fd8e4
Revises: f600727ca04a
Create Date: 2026-05-24 10:02:08.459965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bd634fd8e4'
down_revision: Union[str, Sequence[str], None] = 'f600727ca04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'puls_is_normal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'pressure_is_normal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pressure_is_normal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'puls_is_normal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
