"""fix medication, user  models ad schemas 

Revision ID: 245875e4e5b1
Revises: 57948ac8dc6e
Create Date: 2026-04-25 13:39:50.047921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245875e4e5b1'
down_revision: Union[str, Sequence[str], None] = '57948ac8dc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'pressure_is_normal')
    op.drop_column('medications', 'puls_is_normal')
    op.add_column('users', sa.Column('puls_is_normal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pressure_is_normal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pressure_is_normal')
    op.drop_column('users', 'puls_is_normal')
    op.add_column('medications', sa.Column('puls_is_normal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('medications', sa.Column('pressure_is_normal', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
