"""update medication, user  models ad schemas 

Revision ID: 57948ac8dc6e
Revises: c5d58d654ce4
Create Date: 2026-04-25 13:11:10.593429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57948ac8dc6e'
down_revision: Union[str, Sequence[str], None] = 'c5d58d654ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('puls_is_normal', sa.Integer(), nullable=True))
    op.add_column('medications', sa.Column('pressure_is_normal', sa.String(), nullable=True))
    op.drop_column('users', 'puls_is_normal')
    op.drop_column('users', 'pressure_is_normal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pressure_is_normal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('puls_is_normal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('medications', 'pressure_is_normal')
    op.drop_column('medications', 'puls_is_normal')
    # ### end Alembic commands ###
