"""add puls and pressure

Revision ID: 579884413cb0
Revises: 4e79f9b508dd
Create Date: 2026-04-23 18:01:17.813438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579884413cb0'
down_revision: Union[str, Sequence[str], None] = '4e79f9b508dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем именно те столбцы, которые ты прописал в модели
    op.add_column('symptom_entries', sa.Column('puls_is_normal', sa.Integer(), nullable=True))
    op.add_column('symptom_entries', sa.Column('pressure_is_normal', sa.String(), nullable=True))
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('regular_medications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allergies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('diagnosis', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('medications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medications_pkey'))
    )
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=False)
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('symptom_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('symptom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sleep_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('medications_taken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_insights', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('symptom_entries_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('symptom_entries_pkey'))
    )
    op.create_index(op.f('ix_symptom_entries_id'), 'symptom_entries', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('plan_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
