"""add puls and pressure fields

Revision ID: c5d58d654ce4
Revises: 579884413cb0
Create Date: 2026-04-24 08:05:08.731864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d58d654ce4'
down_revision: Union[str, Sequence[str], None] = '579884413cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptom_entries', 'pulse')
    op.drop_column('symptom_entries', 'pressure')
    op.add_column('users', sa.Column('puls_is_normal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pressure_is_normal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pressure_is_normal')
    op.drop_column('users', 'puls_is_normal')
    op.add_column('symptom_entries', sa.Column('pressure', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('symptom_entries', sa.Column('pulse', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
