"""fix all model rerite on mapped 

Revision ID: f600727ca04a
Revises: 245875e4e5b1
Create Date: 2026-04-26 11:21:39.870775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f600727ca04a'
down_revision: Union[str, Sequence[str], None] = '245875e4e5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('medications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('symptom_entries', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('symptom_entries', 'severity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('symptom_entries', 'sleep_quality',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('symptom_entries', 'sleep_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('symptom_entries', 'stress_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('symptom_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('symptom_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'plan_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'puls_is_normal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'pressure_is_normal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'pressure_is_normal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'puls_is_normal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'plan_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('symptom_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('symptom_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('symptom_entries', 'stress_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('symptom_entries', 'sleep_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('symptom_entries', 'sleep_quality',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('symptom_entries', 'severity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('symptom_entries', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('medications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
