FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt

FROM python:3.11-slim

WORKDIR /app/backend

RUN useradd -m myuser

COPY --from=builder --chown=myuser:myuser /root/.local /home/myuser/.local
COPY --chown=myuser:myuser backend ./backend

USER myuser

ENV APP_DEBUG=False
ENV PORT=8000
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH=/home/myuser/.local/bin:$PATH

EXPOSE 8000

CMD ["uvicorn", "app.services.main:app", "--host", "0.0.0.0", "--port", "8000"]
